# Generated by Django 4.0.2 on 2022-02-07 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('uv_index', models.IntegerField()),
                ('rain_index', models.IntegerField()),
            ],
        ),
    ]
