# Generated by Django 4.0.2 on 2022-02-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='pm10',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='pm100',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='pm25',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='pressure',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='visible_light',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
